### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MaksimKiselev**
Fix cli command to require package.

### CODE REVIEW

**Comment by MaksimKiselev** [comment]
Hello, @Insolita !

Maybe better use carret(^) operator instead tilde(~)?

Maybe better use short syntax `composer require` instead `php composer.phar require` because in my practice composer often was installed globally.

**Comment by Insolita** [comment]
This is tool for develop, it should never use in production, so i think tilda - is right. I don't think that there will be any active changes, except for bugfixes

**Comment by MaksimKiselev** [comment]
@Insolita ok. How about short syntax?

**Comment by Insolita** [comment]
short syntax for what?

**Comment by MaksimKiselev** [comment]
@Insolita for composer require command:

use `composer require` instead `php composer.phar require`

**Comment by Insolita** [comment]
it was standard  part of readme from 
[Standard gii extension template](https://github.com/yiisoft/yii2-gii/tree/master/generators/extension/default) . only with "dev" recomendation
Those who have not learned to use the composer do not need fixtures.
It seems to me that these are very insignificant things

**Comment by MaksimKiselev** [comment]
@Insolita not all good, what get by default)

**Pull request merged**
